server:
  port: 8282

spring:
  application:
    name: ms-wallet

  datasource:
    url: jdbc:mysql://127.0.0.1:3232/wallet_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: mysql
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
